python train.py \
-s /lustre/fs12/portfolios/nvr/projects/nvr_torontoai_3dscenerecon/users/ruilongl/data/360_v2/garden/ \
--root_out outputs/garden \
--exp_name "3dgs_lm_garden" \
--eval \
--images "images_4" \
--resolution 1 \
--image_subsample_size 25 \
--image_subsample_n_iters 4 \
--image_subsample_frame_selection_mode "strided" \
--num_sgd_iterations_before_gn 20000 \
--perc_images_in_line_search 0.3 \
--pcg_rtol 5e-2 \
--pcg_max_iter 8 \
--min_trust_region_radius 1e-4 \
--trust_region_radius 1e-3 \
--max_trust_region_radius 1e-2 \
--iterations 5 \
--test_iterations 0 1 2 3 4 5 \
--save_iterations 0 1 2 3 4 5 \
--checkpoint_iterations 0 1 2 3 4 5